### ISSUE TITLE
manual flag can only be changed explicitly

### ISSUE THREAD

**Issue by cheecheeo** [haskell-compat/mtl-compat#2] opened 2015-04-07 21:20 UTC
I'm running into this problem when I try and build using mtl-compat. I was under the impression that cabal's solver would attempt to try all combinations of dependencies and flags until it either exhausted everything or found a working solution. I don't understand the meaning of the manual flag but I assume that it means that cabal cannot try changing the flag unless the flag is explicitly passed. Is this intentional? Am I depending on mtl-compat in the wrong way?

```
% cabal sandbox init && cabal install --run-tests cgi.cabal
Writing a default package environment file to
/home/jchee/packages/haskell-cgi/cabal.sandbox.config
Using an existing sandbox located at
/home/jchee/packages/haskell-cgi/.cabal-sandbox
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: cgi-3001.2.2.3 (user goal)
next goal: mtl (dependency of cgi-3001.2.2.3)
rejecting: mtl-2.2.1, 2.2.0.1, 2.2 (global constraint requires ==2.1.3.1)
trying: mtl-2.1.3.1
trying: cgi-3001.2.2.3:+network-uri
rejecting: cgi-3001.2.2.3:-old-mtl (conflict: mtl==2.1.3.1,
cgi-3001.2.2.3:old-mtl => mtl>=2.2.1 && <2.3)
trying: cgi-3001.2.2.3:+old-mtl
trying: mtl-compat-0.2.1.3 (dependency of cgi-3001.2.2.3:+old-mtl)
trying: mtl-compat-0.2.1.3:-two-point-one
rejecting: mtl-compat-0.2.1.3:-two-point-two (conflict: mtl==2.1.3.1,
mtl-compat-0.2.1.3:two-point-two => mtl>=2.2.1 && <2.3)
rejecting: mtl-compat-0.2.1.3:+two-point-two (manual flag can only be changed
explicitly)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
```

**Comment by RyanGlScott** [comment] 2015-04-07 21:38
I'm not sure what's going on there. I'd need to know more about what version of GHC/`cgi`/flags you're using, since I can't reproduce that error when running `cabal install cgi.cabal -fold-compat --dry-run` in a fresh `cgi` sandbox (I tried the versions from Hackage and from the `haskell-cgi` repo).

As far as how the flags work, my understanding is that `cabal` isn't smart enough to try all combinations of flags when resolving dependencies. That's why I adopt the convention that `transformers-compat` has and upload three versions of `mtl-compat` that are considered current. Version 0.2.1.3 has no flags on by default, version 0.2.1.2 has the `two-point-two` flag on by default, and version 0.2.1.1 has the `two-point-one` flag on by default. If all goes well, `cabal` should always pick one of those three packages, depending on which version of `mtl` you have installed.

**Comment by cheecheeo** [comment] 2015-04-07 22:10
I'm using commit `4441ada6adacf93d7edce0e1f8b21ab11ecff998` of `git@github.com:cheecheeo/haskell-cgi.git`

Cabal version:

```
% cabal --version
cabal-install version 1.22.0.1
using version 1.22.1.1 of the Cabal library 
```

Once all that's done, I've also downloaded: wget https://www.stackage.org/nightly/cabal.config which pins mtl-compat:

```
% cat cabal.config| grep mtl-compat
             mtl-compat ==0.2.1.3,
```

And then run:

```
% cabal sandbox init && cabal install --run-tests cgi.cabal
```

In a clean sandbox. If that doesn't reproduce the problem it might be something else messed up in my environment.

I'm linking the stackage issue for context: https://github.com/fpco/stackage/pull/522#issuecomment-90392831

**Comment by RyanGlScott** [comment] 2015-04-07 22:46
Ah, I didn't realize that you were using Stackage. Examining the nightly `.config` file, I think I see what the problem is: Stackage is requiring `mtl ==2.1.3.1` and `mtl-compat ==0.2.1.3` to be used together, which won't work for the reasons I mention above. If Stackage changed the requirement to `mtl-compat ==0.2.1.1`, I think that would fix the problem.

I'll follow up with this on the `stackage` issue you created.

**Comment by cheecheeo** [comment] 2015-04-07 23:11
Thanks @RyanGlScott

**Closed as completed** 2015-04-07 23:11 UTC
